# Generated by Django 5.0.3 on 2024-04-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_images_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
